services:

  dev-nodejs:
    container_name: dev_nodejs
    hostname: db_nodejs
    build:
      context: dev-nodejs
      dockerfile: Dockerfile.dev
    secrets:
      - db-password
    depends_on:
      - db


  dev-python:
    container_name: dev_python2
    hostname: db_python2
    build:
      context: dev-python
      dockerfile: Dockerfile.dev
    secrets:
      - db-password
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306

  proxy:
    build: proxy
    ports:
      - 8083:80
    depends_on:
      - dev-nodejs
      - dev-python
      
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
